export const DATA = [
  {
    id: "3ac68afc-qc605-48d3-a4f8-fbd91aa97f63",
    image: "../../assets/med.jpg",
    description: "some description",
    title: "Paracetamol",
    prescription:true,
  },
  {
    id: "3ac68afc-c60q5-48d3-a4f8-fbd91aa97f63",
    image: "../../assets/med.jpg",
    description: "some description",
    title: "Paracetamol",
    prescription:false,
  },
  {
    id: "3ac68afc-c6205-48d3-a4f8-fbd91aa97f63",
    image: "../../assets/med.jpg",
    description: "some description",
    title: "Paracetamol",
    prescription:false,
  },
  {
    id: "3ac68afc-c2605-48d3-a4f8-fbd91aa97f63",
    image: "../../assets/med.jpg",
    description: "some description",
    title: "Paracetamol",
    prescription:true,
  },
  {
    id: "3ac268afc-c2605-48d3-a4f8-fbd91aa97f63",
    image: "../../assets/med.jpg",
    description: "some description",
    title: "Paracetamol",
    prescription:false,
  },
  {
    id: "3a1c68afc-c605-48d3-a4f8-fbd911aa97f63",
    image: "../../assets/med.jpg",
    description: "some description",
    title: "Paracetamol",
    prescription:false,
  },
  {
    id: "3ac681afc-c605-148d3-a4f8-fbd91aa97f63",
    image: "../../assets/med.jpg",
    description: "some description",
    title: "Paracetamol",
    prescription:false,
  },
];
